name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag mruby-cli:$(date +%s)
    - name: Build Test binary
      run: docker run --rm -v $(pwd)/test:/test mruby-cli make -C /test
    - name: Running Test binary
      run: ls -la $(pwd)/test
